version: '3.9'

services:
  db:
    image: postgres:16
    container_name: futebol_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: futebol
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../sql:/docker-entrypoint-initdb.d  

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: futebol_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    image: python:3.13-slim
    container_name: futebol_app
    working_dir: /app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: futebol
      DB_USER: admin
      DB_PASSWORD: admin123
      APP_NON_INTERACTIVE: "1"
      APP_AUTO_RUN: "1,2,3,4,5,6,7,8,9,10,11,12,13"
      APP_PARTIDA_ID: "1"
    volumes:
      - ../app:/app
      - ../requirements.txt:/requirements.txt:ro
    depends_on:
      - db
    command: bash -c "pip install --no-cache-dir -r /requirements.txt && python main.py"

volumes:
  postgres_data:
